[build.environment]
  NEXT_PUBLIC_WP_API_URL   = "https://cms.selfify.id/wp-json/wp/v2"
  NEXT_PUBLIC_GRAPHQL_URL  = "https://cms.selfify.id/graphql"

[build]
  command   = "npm run build"
  publish   = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
